# Generated by Django 4.2.1 on 2023-05-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('meet', '0005_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='periodic_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
