# Generated by Django 4.2.1 on 2023-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_alter_room_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type_of',
        ),
        migrations.AddField(
            model_name='room',
            name='remind_before',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
