# Generated by Django 4.2.1 on 2023-05-21 16:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('meet', '0008_remove_room_type_of_room_remind_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='room',
            name='periodic_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='django_celery_beat.periodictask', verbose_name='periodic_task'),
        ),
        migrations.AlterField(
            model_name='room',
            name='remind_before',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='remind_before'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.TimeField(null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='weekdays'),
        ),
    ]
