# Generated by Django 4.2.1 on 2023-05-22 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0009_alter_room_created_at_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='room_members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
