@startuml system

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material

!include FONTAWESOME/cc_stripe.puml
!include MATERIAL/email.puml

title "Coax Meet System"

Person(user, "User", "The user of Coax Meet")
System(smart_code, "Coax Meet", "The system of Coax Meet")

Rel_D(user, smart_code, "Uses the system")

@enduml